//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreownTutor.Data.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartInfomation
    {
        public int CartID { get; set; }
        public int NoOfItems { get; set; }
        public long TotalPrice { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public bool IsItemDelivered { get; set; }
    }
}
