//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreownTutor.Data.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string Location { get; set; }
        public string ContactDetails { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Gender { get; set; }
        public byte[] ProfileImage { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> CourseID { get; set; }
    }
}
