//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreownTutor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.LiveSessions = new HashSet<LiveSession>();
            this.CourseRegistrations = new HashSet<CourseRegistration>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<int> NoOfChapters { get; set; }
        public Nullable<System.DateTime> DurationOfCourse { get; set; }
        public Nullable<int> NoOfAttendees { get; set; }
        public string TypeOfCourse { get; set; }
        public string Language { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> CreatedDateAndTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> AttendessLimit { get; set; }
        public Nullable<double> CoursePrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiveSession> LiveSessions { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual Course Course2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRegistration> CourseRegistrations { get; set; }
    }
}
