//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreownTutor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public int ReviewRating { get; set; }
        public string ReviewComments { get; set; }
        public string UserID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<System.DateTime> AddedTime { get; set; }
        public Nullable<int> ReviewAddedBy { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
