//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreownTutor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int TestID { get; set; }
        public string TestName { get; set; }
        public string TestDescription { get; set; }
        public string TestInstructions { get; set; }
        public bool AllowViewingAnswer { get; set; }
        public bool IsTimeAlloted { get; set; }
        public int Marks { get; set; }
        public decimal Percentage { get; set; }
        public bool Result { get; set; }
        public bool PaymentType { get; set; }
        public string UserID { get; set; }
        public string Category { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<int> Seconds { get; set; }
    }
}
